hub:
  spawn:
    x: 0
    y: 100
    z: 0
computer:
  location:
    x: 0
    y: 100
    z: 0
  vents:
    - :
      - x: 0
        y: 100
        z: 0
      - x: 0
        y: 100
        z: 0
    - :
      - x: 0
        y: 100
        z: 0
      - x: 0
        y: 100
        z: 0
